name: yoliday_app
description: A  app that matches the provided design in figma.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #         weight: 700